import { Service } from "./service";

// Generated by https://quicktype.io

export interface Employee {
    id:          number;
    name:        string;
    password:    string;
    designation: string;
}
