// Generated by https://quicktype.io

export interface Interaction {
    id:       number;
    clientId: number;
    empId:    number;
    intType:  string;
    intDate:  string;
    remarks:  string;
    client:   null;
    employee: null;
}
